// Catalog-wide search completeness diagnostics.
//
// Goal: prove that searching a champion's name surfaces EVERY one of its skins,
// and searching a skin line surfaces EVERY skin in that line — across the whole
// catalog, not a handful of hand-picked names.
//
// This suite is intentionally DIAGNOSTIC. It runs against a committed snapshot
// of the live catalog (./__fixtures__/catalog.json, regenerated by
// scripts/gen-search-fixture.mjs) and is split into three layers:
//
//   1. Matching layer (uncapped): the searcher, given no result limit, MUST
//      find every skin. These assertions should PASS — they prove the matcher
//      itself is sound and the data is correctly associated.
//
//   2. UI caps: re-run with the command palette's real result cap. The cap is
//      sized (MAX_SKINS=50) to exceed the largest champion roster (23) and skin
//      line (36), so no real group is ever truncated. Guards against a future
//      cap regression; on failure the message lists every truncated champion.
//
//   3. Skin lines: every skin's skin line(s) are indexed into its searchable
//      text, so searching a line name surfaces every member — even those whose
//      display name doesn't carry the line. Guards that contract; on failure
//      the message lists every skin unfindable by its line's name.
//
// If a block ever fails, the full inventory is written to web/.data/*.report.json.

import { describe, it, expect } from 'vitest'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createSearcher } from './index'
import { championDisplayName, displaySkinName } from '../skinName'
import catalog from './__fixtures__/catalog.json'

interface FixtureSkin {
  id: string
  championId: string
  championName: string
  num: number
  name: string
  sets: string[]
}
const SKINS = catalog.skins as FixtureSkin[]

const REPORT_DIR = join(process.cwd(), '.data')
const writeReport = (file: string, data: unknown) => {
  try {
    writeFileSync(join(REPORT_DIR, file), JSON.stringify(data, null, 2) + '\n')
  } catch {
    /* report is a convenience; never fail the suite over it */
  }
}

// ─── UI search configs, replicated faithfully ────────────────────────────────

// Command palette skin entries — CommandPalette.tsx lines 116-128.
//   label   = displaySkinName(name, championId)
//   haystack= `${label} ${championDisplayName(championId)}`.toLowerCase()
interface PaletteEntry {
  skinId: string
  championId: string
  label: string
  haystack: string
}
const paletteEntries: PaletteEntry[] = SKINS.map((s) => {
  const label = displaySkinName(s.name, s.championId)
  return {
    skinId: s.id,
    championId: s.championId,
    label,
    // Mirror CommandPalette: index skin name + champion name + skin lines.
    haystack: `${label} ${championDisplayName(s.championId)} ${s.sets.join(' ')}`.toLowerCase(),
  }
})
const MAX_SKINS = 50 // CommandPalette.tsx — covers the largest champion/skin-line group
const paletteSearcher = (limit?: number) =>
  createSearcher(paletteEntries, { keys: ['label', 'haystack'], limit })

// Guess box (Splashdle / Chroma Vision) — GuessKit.tsx lines 207-219.
//   keys name(0.7)/championName(0.3), prefixFirst, limit 8, minLength 2.
//   name = raw skin name, championName = DB display name.
interface GuessEntry {
  skinId: string
  championId: string
  name: string
  championName: string
}
const guessEntries: GuessEntry[] = SKINS.map((s) => ({
  skinId: s.id,
  championId: s.championId,
  name: s.name,
  championName: s.championName,
}))
const GUESS_LIMIT = 8
const guessSearcher = (limit?: number) =>
  createSearcher(guessEntries, {
    keys: [
      { name: 'name', weight: 0.7 },
      { name: 'championName', weight: 0.3 },
    ],
    prefixFirst: true,
    limit,
    minLength: 2,
  })

// ─── grouping helpers ─────────────────────────────────────────────────────────

const byChampion = new Map<string, FixtureSkin[]>()
for (const s of SKINS) {
  const arr = byChampion.get(s.championId) ?? []
  arr.push(s)
  byChampion.set(s.championId, arr)
}

const bySet = new Map<string, FixtureSkin[]>()
for (const s of SKINS) {
  for (const set of s.sets) {
    const arr = bySet.get(set) ?? []
    arr.push(s)
    bySet.set(set, arr)
  }
}

// ─── 1. matching layer (uncapped) — should PASS ───────────────────────────────

describe('champion search — matching layer (uncapped)', () => {
  it('finds every skin of every champion when no result cap is applied', () => {
    const search = paletteSearcher(undefined)
    const failures: Array<{ champion: string; missing: string[] }> = []

    for (const [championId, skins] of byChampion) {
      const found = new Set(
        search.search(championDisplayName(championId)).map((e) => e.skinId),
      )
      const missing = skins
        .filter((s) => !found.has(s.id))
        .map((s) => displaySkinName(s.name, s.championId))
      if (missing.length) failures.push({ champion: championDisplayName(championId), missing })
    }

    if (failures.length) writeReport('search-gaps-champion-matching.report.json', failures)
    expect(failures, summarize('champions with unmatchable skins (uncapped)', failures)).toEqual([])
  })
})

// ─── 2. UI caps — FAILS today, message is the truncation inventory ────────────

describe('champion search — real UI result caps', () => {
  it('command palette (MAX_SKINS=10) shows every skin for every champion', () => {
    const search = paletteSearcher(MAX_SKINS)
    const truncated: Array<{ champion: string; total: number; shown: number; hidden: string[] }> = []

    for (const [championId, skins] of byChampion) {
      const found = new Set(
        search.search(championDisplayName(championId)).map((e) => e.skinId),
      )
      const hidden = skins.filter((s) => !found.has(s.id))
      if (hidden.length) {
        truncated.push({
          champion: championDisplayName(championId),
          total: skins.length,
          shown: skins.length - hidden.length,
          hidden: hidden.map((s) => s.name),
        })
      }
    }

    if (truncated.length) writeReport('search-gaps-palette-cap.report.json', truncated)
    expect(
      truncated,
      summarize(`champions truncated by the palette's ${MAX_SKINS}-result cap`, truncated),
    ).toEqual([])
  })

  // The guess box is a *narrowing* autocomplete for a guessing game, not a
  // browse surface — its 8-row cap is intentional. The contract is "an exact
  // skin name resolves, and a champion prefix surfaces its skins up to the
  // cap", NOT exhaustiveness.
  it('guess box resolves an exact skin name and narrows by champion', () => {
    const search = guessSearcher(GUESS_LIMIT)
    expect(search.search('Bewitching Batnivia').some((e) => e.skinId === '34037')).toBe(true)
    const anivia = search.search('Anivia')
    expect(anivia.length).toBeGreaterThan(0)
    expect(anivia.length).toBeLessThanOrEqual(GUESS_LIMIT)
  })
})

// ─── 3. skin lines — FAILS today, message is the unfindable inventory ─────────

describe('skin line search', () => {
  it('finds every skin in a line by searching the line name', () => {
    const search = paletteSearcher(undefined) // uncapped: isolate findability from caps
    const gaps: Array<{ line: string; total: number; unfindable: string[] }> = []

    for (const [set, skins] of bySet) {
      const found = new Set(search.search(set).map((e) => e.skinId))
      const unfindable = skins.filter((s) => !found.has(s.id)).map((s) => `${s.name} (${s.championName})`)
      if (unfindable.length) gaps.push({ line: set, total: skins.length, unfindable })
    }

    if (gaps.length) writeReport('search-gaps-skinline.report.json', gaps)
    const unfindableCount = gaps.reduce((n, g) => n + g.unfindable.length, 0)
    expect(
      gaps,
      summarize(
        `skin lines with members unfindable by line name (${unfindableCount} skins across ${gaps.length} lines)`,
        gaps,
      ),
    ).toEqual([])
  })
})

// ─── 4. named edge cases — regression lock ────────────────────────────────────

describe('named edge cases', () => {
  const search = paletteSearcher(undefined)
  const findsSkinByName = (query: string, skinName: string) =>
    search.search(query).some((e) => e.label.toLowerCase() === skinName.toLowerCase())

  // The reported example: an Anivia skin whose name shares no token with "Anivia".
  it('"anivia" finds Bewitching Batnivia (uncapped matching layer)', () => {
    expect(findsSkinByName('anivia', 'Bewitching Batnivia')).toBe(true)
  })

  for (const champ of ['Kai’Sa', 'Bel’Veth', 'Kha’Zix', 'Cho’Gath']) {
    it(`apostrophe champion "${champ}" returns at least one skin`, () => {
      expect(search.search(champ).length).toBeGreaterThan(0)
    })
  }

  it('"wukong" (DDragon id MonkeyKing) returns skins', () => {
    expect(search.search('wukong').length).toBeGreaterThan(0)
  })

  it('"nunu" returns skins (id Nunu → "Nunu & Willump")', () => {
    expect(search.search('nunu').length).toBeGreaterThan(0)
  })
})

// Compact, readable failure message: counts + a capped preview, full list in
// the .report.json files written above.
function summarize(headline: string, rows: unknown[]): string {
  const preview = rows.slice(0, 15)
  const more = rows.length > preview.length ? `\n  …and ${rows.length - preview.length} more` : ''
  return `${rows.length} ${headline}:\n${JSON.stringify(preview, null, 2)}${more}\n(full inventory in web/.data/*.report.json)`
}
